# Generated by Django 6.0.3 on 2026-03-17 07:32

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=posts.models.unusable_password, max_length=128),
        ),
    ]
